### ISSUE TITLE
How to polyfill `Element.ariaDescribedByElements` and co

### ISSUE THREAD

**Issue by caridy** [a11y-api/a11y-api#105]
@alice this question came up yesterday while discussing the update of the proposal with some folks internally. At first glance is seems that polyfilling them with the current implementation of shadow dom shipped in Chrome and Safari, will not be possible. But I will want confirm that.

/cc @SiTaggart

**Comment by robdodson** [comment]
I have ideas but they're not pretty...

If I set ariaDescribedbyElements on a node inside the shadow root, then that setter could also spawn a visibly hidden `<span>` inside of that shadow root with a uniquely generated ID that grabs the text content from all of the nodes in the ariaDescribedbyElements array. This span could then be associated using aria-describedby. You would likely also need to install MutationObservers on all of the nodes in the ariaDescribedbyElemenets array, so if their text changed or they were removed from the document, the `<span>`'s text would be updated as well.

**Comment by SiTaggart** [comment]
So we'd get duplicate content for AT users who navigation / explore the page? You'd get the description from the described element, find the spawned copied, and then find the original descriptions that are out of the shadow root. 

That does sound very sub-optimal

**Comment by robdodson** [comment]
I think you would only hear the copy once under polyfill, at least that's how i'm envisioning it.

**Comment by alice** [comment]
I'm not 100% clear on the original question...
- Polyfilling `ariaFooElements` would obviously have to be low-fidelity, as you'd need to use the `aria-foo` attribute and assign IDs to the elements, but I assume that's not what you're asking.
- Polyfilling in such a way that you can cross shadow DOM boundaries - I think Rob has a reasonable idea: duplicate the target elements in the scope you need them, then refer to them by ID. You could even make those extra elements just straight up `hidden` (i.e. `display: none`), since the text computation spec [allows hidden nodes to be referenced](https://www.w3.org/TR/accname-aam-1.1/#step2A) in name or description calculation. (http://output.jsbin.com/nenuxaq is a demo of this - check the accessible properties for the :rainbow: button.)

**Comment by caridy** [comment]
@SiTaggart I think @robdodson is right! we create the hidden element inside the shadow, generate an ID for that one, and set the aria-foo to that ID to connect them. The reader will only read the one reachable inside the shadow.

I'm closing this one, that seems reasonable for me, and it is pretty close to what we had in mind.

**Comment by SiTaggart** [comment]
Sure, using `hidden` on the cloned description would be ideal. I've tested this before for a variety of different reasons, and only Voice Over actually treated it correctly. From memory JAWS and possible NVDA treated `hidden` as if it wasn't there so the description wasn't spoken.

So yeah, it's a solution that's on spec but doesn't actually work for users.
