### ISSUE TITLE
Will it bring more circle dependencies or memory leak issues?

### ISSUE THREAD

**Issue by Jinjiang** [a11y-api/a11y-api#113]
Because the references from another DOM element still exist when it is removed from the DOM tree.
Thanks.

**Comment by cookiecrook** [comment]
Can you be more specific about your concern? Object references can be nullified when the backing object is destroyed.

**Comment by Jinjiang** [comment]
For example I have two elements A and B. Now I would set B as the error message of A. So I can write: `A.accessibleNode.errorMessage = B`. Later I may remove B for some reason but not update `A.accessibleNode.errorMessage` by mistake. So the reference of B would still be hold in memory by `A.accessibleNode.errorMessage`. It will easily lead memory issues.
Am I right?
Thanks.

**Comment by cookiecrook** [comment]
That's what I thought you meant. Here's why I think it's not a spec problem. All rendering engines I am aware of have a way to implement weak references that can be garbage collected with the non-retaining relation is nullified. I think an issue like the one you mention would be an implementation bug in the specific browser engine rather than a problem with the spec. 

If you still think there is a problem with the spec, or if you know of a rendering engine where this would be unimplementable, we can re-open this issue.
