### ISSUE TITLE
Relationship of Accessible Input Events and IndieUI Events?

### ISSUE THREAD

**Issue by patrickhlauke** [a11y-api/a11y-api#48]
More of a question perhaps, but: what is the relationship between Accessible Input Events and IndieUI Events https://www.w3.org/TR/indie-ui-events/ ?

I seem to remember that the scope for IndieUI Events was scaled back, but I thought the whole idea of having events relating to *intent*, rather than input-device-specific handlers, was going to be done by IndieUI.

**Comment by minorninth** [comment]
IndieUI events didn't succeed. I think there were some good ideas there but ultimately the group wasn't able to come up with a proposal that enough people could get behind.

The AOM is less ambitious. It allows web authors to listen for specific input events that can be generated by assistive technology or other accessibility clients. We also intend for it to formalize exactly what DOM input events are generated as fallbacks for these events so that all browsers can agree.

For example, the AOM would allow authors to explicitly listen for a "dismiss dialog" event, but if it's unhandled it might trigger an "Esc" keypress.

At some point in the future if something like Indie UI was revived, it could sit in-between AOM events and DOM events, i.e. "accessible dismiss dialog" could trigger a "dismiss dialog" intent if unhandled, which could trigger an "Esc" keypress if unhandled.
